[package]
name = "pixel-arranger"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.21.0"
image = "0.24.6"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"

[workspace]
