[package]
name = "pixel-arranger"
version = "0.1.0"
edition = "2018"

[dependencies]
egui = "0.15.0"
euc = "0.4.5"
image = "0.23.14"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"

[workspace]
