name: docs

on:
  push:
    branches:
      - main

jobs:
  deploy-documentation:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          override: true
          toolchain: nightly

      - name: Install `mdbook`
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Build docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all-features

      - name: Build book and documentation
        run: |
          cd book
          mdbook build
          mkdir -p book/rustdoc
          cp -r ../target/doc/* book/rustdoc/

      - name: Generate documentation artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: book/book

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
